---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-deployment
spec:
  replicas: 2
  selector:
     matchLabels:
         app: uber
  template: 
    metadata:
      labels:
        app: uber
    spec: 
      containers:
      - name: uber
        image: gouthamc125/uber:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: uber-service
spec:
  selector:
    app: uber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
